apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-kafka-adapter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "prometheus-kafka-adapter.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.env.KAFKA_TLS_CLIENT_KEY_PASS }}
  KAFKA_TLS_CLIENT_KEY_PASS: {{ .Values.env.KAFKA_TLS_CLIENT_KEY_PASS | b64enc }}
{{- end }}{{- if .Values.env.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_USERNAME: {{ .Values.env.BASIC_AUTH_USERNAME | b64enc }}
{{- end }}{{- if .Values.env.BASIC_AUTH_PASSWORD }}
  BASIC_AUTH_PASSWORD: {{ .Values.env.BASIC_AUTH_PASSWORD | b64enc }}
{{- end }}
